name: lp

on:
  push:
    branches:
      - "main"

jobs:
  test:
    name: Test Ubuntu with Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo snap install solc
          pip3 install slither-analyzer

      - name: Install
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build
      - name: Run code analysis
        run: yarn analyze
      - name: Run coverage
        run: yarn coverage
